### Obtener todas las tareas
GET http://127.0.0.1:8000/api/tareas/?last_doc_id=SBnd8fj5JGCaDa8ZivSC
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLXNlbmEtNmQ4YWUiLCJhdWQiOiJhcGktc2VuYS02ZDhhZSIsImF1dGhfdGltZSI6MTc3Mjc0NTk5MiwidXNlcl9pZCI6IlYwRWtkbzRnREtPcTZLbURxeDBtY0hQY2lNYjIiLCJzdWIiOiJWMEVrZG80Z0RLT3E2S21EcXgwbWNIUGNpTWIyIiwiaWF0IjoxNzcyNzQ1OTkyLCJleHAiOjE3NzI3NDk1OTIsImVtYWlsIjoianJtbUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsianJtbUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.R1m3CFINts6tz5n_vQYurnm0MEhFDlVM3poJ-Z9gKjlgD8CSixZapyvST8KilyeH16oJaGEgY99EHMOHK4KVX7OwsIyCn74dd_hadQw1enyj-FAE1tnaWVGy7ewq4HbHBQJthnTTUuXgnW5ro6W4vqwul3F77JQp-Mp5LDl4kEqrD0CfPJjZ1wWDeG52KvalqXp9h7-PgwJPZICQpEGU3YoOEoQx2M9_-1Y7WrR-mKiKcJIINY59HWu4y66qF1Nm6C9WRtVUO0Ryf0WJ8l75_EdqiN522cALrRinrpjbD8w1yU_JOWKTjg2h6AVsDzit_96pZ9X4dmZlYUDNjsYu_w

### Registrarse
POST http://127.0.0.1:8000/api/auth/registro/
Content-Type: application/json

{
    "email": "jrmm@gmail.com",
    "password": "jrmm2008"
}

### 2. Iniciar sesión para conseguir el Token (POST)
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email": "jrmm@gmail.com",
    "password": "jrmm2008"
}

### 3. Crear una tarea USANDO EL TOKEN (POST)
POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLXNlbmEtNmQ4YWUiLCJhdWQiOiJhcGktc2VuYS02ZDhhZSIsImF1dGhfdGltZSI6MTc3Mzk1NDk3NSwidXNlcl9pZCI6IlYwRWtkbzRnREtPcTZLbURxeDBtY0hQY2lNYjIiLCJzdWIiOiJWMEVrZG80Z0RLT3E2S21EcXgwbWNIUGNpTWIyIiwiaWF0IjoxNzczOTU0OTc1LCJleHAiOjE3NzM5NTg1NzUsImVtYWlsIjoianJtbUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsianJtbUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.GsK9CcusP5FAmq0kJFTyHfnpuwbGDrENi0XbDjosrU00RDvqRB4C09XmQR2yfWXvzp_Kb8LcGGtHBFrMQEgRRN42nOTIHq9AM3qZ_clmWDIg0KKyaHHMgI5uWP9DrKiPTKRhnXuFww5lxXufFc60eSXiUGtYAxNpQNAltY6kkt8pUzOMJEHBBxRSnzK5eBxH192rS8MRs6bJEYNziDpoxQhKTNrhcU0wOFcweUDUhoTrM76eQJmFXActvlqBJBPAYyeh0CVWd1XLiEMHrfyEejggzaZjAAqNwimqYz7nKZ2BWNHNCeJqkeC1pEsh12WAUqMuKTSBEDNGOrcOGrPSaA

{
    "titulo": "Tarea 6",
    "descripcion": "Esta tarea es más estructurada, ya que es para probar el funcionamiento de la app movil aisduh fuidshiofjdiohfiodhsoij foisdjiodjoisdjoifjdoi fjdi jdio jfoidj ojkdsfoi oij eoijkdo nioj oifjoifj oiewhiouhfoiej fo83n oiejfidji fhewiom kdji0fjewiu okdmoif j3ijfid jfiewj idjfio mei iewk iouoi di0u iwej fi0ewu fkdjfi0whuirmdof whifjwnfiwjifjew9f jiejfpkej'9f owiej fiejf iewj fiewif"
}

### Foto de perfil
POST http://127.0.0.1:8000/api/perfil/foto/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLXNlbmEtNmQ4YWUiLCJhdWQiOiJhcGktc2VuYS02ZDhhZSIsImF1dGhfdGltZSI6MTc3Mjc0NTk5MiwidXNlcl9pZCI6IlYwRWtkbzRnREtPcTZLbURxeDBtY0hQY2lNYjIiLCJzdWIiOiJWMEVrZG80Z0RLT3E2S21EcXgwbWNIUGNpTWIyIiwiaWF0IjoxNzcyNzQ1OTkyLCJleHAiOjE3NzI3NDk1OTIsImVtYWlsIjoianJtbUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsianJtbUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.R1m3CFINts6tz5n_vQYurnm0MEhFDlVM3poJ-Z9gKjlgD8CSixZapyvST8KilyeH16oJaGEgY99EHMOHK4KVX7OwsIyCn74dd_hadQw1enyj-FAE1tnaWVGy7ewq4HbHBQJthnTTUuXgnW5ro6W4vqwul3F77JQp-Mp5LDl4kEqrD0CfPJjZ1wWDeG52KvalqXp9h7-PgwJPZICQpEGU3YoOEoQx2M9_-1Y7WrR-mKiKcJIINY59HWu4y66qF1Nm6C9WRtVUO0Ryf0WJ8l75_EdqiN522cALrRinrpjbD8w1yU_JOWKTjg2h6AVsDzit_96pZ9X4dmZlYUDNjsYu_w
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="avatar.jpg"
Content-Type: image/jpeg

< C:\Users\JRMM\OneDrive\Escritorio\SENA 3147269\Cristian\avatar.jpg
--MiBoundary--