### Obtener todas las tareas
GET http://127.0.0.1:8000/api/tareas/?last_doc_id=SBnd8fj5JGCaDa8ZivSC
Authorization: Bearer 

### Registrarse
POST http://127.0.0.1:8000/api/auth/registro/
Content-Type: application/json

{
    "email": "jrmm@gmail.com",
    "password": "jrmm2008"
}

### 2. Iniciar sesión para conseguir el Token (POST)
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email": "jrmm@gmail.com",
    "password": "jrmm2008"
}

### 3. Crear una tarea USANDO EL TOKEN (POST)
POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json
Authorization: Bearer 

{
    "titulo": "Tarea 6",
    "descripcion": "Esta tarea es más estructurada, ya que es para probar el funcionamiento de la app movil aisduh fuidshiofjdiohf"
}

### 4. Actualizar tarea
PUT http://127.0.0.1:8000/api/tareas/72SFev8Ydw5FPdOFgYV0/
Content-Type: application/json
Authorization: Bearer 

{
    "titulo": "Tarea actualizada",
    "descripcion": "Esta tarea a sido actualizada"
}

### 5. Eliminar tarea
DELETE http://127.0.0.1:8000/api/tareas/72SFev8Ydw5FPdOFgYV0/
Authorization: Bearer 

### Foto de perfil
POST http://127.0.0.1:8000/api/perfil/foto/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLXNlbmEtNmQ4YWUiLCJhdWQiOiJhcGktc2VuYS02ZDhhZSIsImF1dGhfdGltZSI6MTc3NDE1NDIzOSwidXNlcl9pZCI6Ik9UQklZNm42QnBjdlpVbGEycHI1VFdnbG01TTIiLCJzdWIiOiJPVEJJWTZuNkJwY3ZaVWxhMnByNVRXZ2xtNU0yIiwiaWF0IjoxNzc0MTU0MjM5LCJleHAiOjE3NzQxNTc4MzksImVtYWlsIjoianJtbUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsianJtbUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.D-OdRXl8iTyxj4mnYBkrc2NdqF_YMlPuVFF_ztFYZvAHgzF04KOnOdvdcmJIBsmzQSDVcK_h7A_0lrKVIBRZ5hfz9a46bmz55nrnDyxD-I5Az5JnywaSMme-uWTbNI0REYYt-GEiTA78hdStP7AUm6iqKEPGMnLPpFBx9VVcMGExBhkZx6Rm8ozuSIqBAM_EykBg7WxchXhvO2sUU9jF0di36vL_Vg70CmmoN0LIn0vofXdod_EYhfbcHXGiFHVY2lFYKK5hIMoHeSum-ynqi7EP_N2fq4PR9zRAmflLH8Bq_XOwDE4kFaRLlX_CSov8Ooox-S7SilZw_qgbHNVGzg
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="avatar.jpg"
Content-Type: image/jpeg

< ./avatar.jpg
--MiBoundary--